In [1]:
import torch

In [3]:
import torch
import numpy as np

device = torch.device("cuda")


In [4]:
# Q1
tensor_test = torch.tensor([1, 2, 3, 4])
reshaped = torch.reshape(tensor_test,(2,2))
print("Reshaped Tensor:\n", reshaped)

tensor1 = torch.tensor([1, 2])
tensor2 = torch.tensor([3, 4])
stacked = torch.stack([tensor1,tensor1], dim=0)
print("Stacked Tensor:\n", stacked)

tensor_to_squeeze = torch.tensor([[[1], [2]]])
squeezed = tensor_to_squeeze.squeeze()
print("Squeezed Tensor:\n", squeezed)

unsqueezed = tensor_test.unsqueeze(1)
print("Unsqueezed Tensor:\n", unsqueezed)


Reshaped Tensor:
 tensor([[1, 2],
        [3, 4]])
Stacked Tensor:
 tensor([[1, 2],
        [1, 2]])
Squeezed Tensor:
 tensor([1, 2])
Unsqueezed Tensor:
 tensor([[1],
        [2],
        [3],
        [4]])


In [5]:
#q2
tensor = torch.randn(1, 2, 3)
print("Original Tensor:")
print(tensor)
print("Original Shape:", tensor.shape)
permuted_tensor = tensor.permute(1, 0, 2) # exention of transpose

print("\nPermuted Tensor:")
print(permuted_tensor)
print("Permuted Shape:", permuted_tensor.shape)


Original Tensor:
tensor([[[ 0.7907, -0.8756,  1.7733],
         [-0.5846, -0.3874, -0.1537]]])
Original Shape: torch.Size([1, 2, 3])

Permuted Tensor:
tensor([[[ 0.7907, -0.8756,  1.7733]],

        [[-0.5846, -0.3874, -0.1537]]])
Permuted Shape: torch.Size([2, 1, 3])


In [6]:
#q3
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor[1][2])


tensor(6)


In [7]:
#q4
np_arr = np.arange(1,10)
tensor = torch.from_numpy(np_arr)
print(tensor)

np_arr = tensor.numpy()
print(np_arr)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
[1 2 3 4 5 6 7 8 9]


In [8]:
#q5
mul1 = torch.randn(7,7)
print(mul1)

tensor([[ 1.1940e+00,  6.1739e-01,  1.6811e+00, -7.3645e-01, -8.4418e-01,
         -4.5116e-02,  3.9766e+00],
        [-1.2754e-01,  5.9657e-01,  1.7933e+00, -7.0790e-01, -1.6980e+00,
         -1.3694e-01,  5.2942e-01],
        [ 2.8334e-01,  5.9107e-01,  2.4724e-01,  3.7716e-01,  5.3026e-01,
          7.8605e-01,  1.2773e+00],
        [ 1.1646e+00,  5.1400e-01, -1.7344e+00, -2.3281e-01,  7.3798e-01,
          7.7033e-01,  1.2809e+00],
        [ 8.9013e-01,  3.8340e-01, -2.0580e-03, -1.1701e+00, -1.5904e+00,
         -5.8878e-01, -9.9941e-01],
        [ 3.1410e-01, -7.0568e-01, -8.0475e-01,  3.5257e-01, -1.5448e+00,
         -8.3645e-01,  2.1048e+00],
        [ 9.1642e-01,  2.2090e-01,  2.6743e+00,  2.9931e-01, -1.9389e+00,
         -2.9716e-01, -1.2205e+00]])


In [9]:
#q6
mul2 = torch.randn(1,7)
prod = torch.matmul(mul1,mul2.permute(1,0))
print(prod)


tensor([[-7.7923],
        [-3.9286],
        [-1.7422],
        [-1.4682],
        [-1.5763],
        [-0.6609],
        [ 0.1406]])


In [10]:
#q7,8
mul1 = torch.randn(7,7).to(device)
mul2 = torch.randn(1,7).to(device)
prod = torch.matmul(mul1,mul2.permute(1,0))
print(prod)


tensor([[ 2.3266],
        [-4.7794],
        [-0.0324],
        [-1.1818],
        [ 0.0959],
        [-3.8096],
        [ 4.1705]])


In [11]:
#q9
print(torch.max(prod))
print(torch.min(prod))


tensor(4.1705)
tensor(-4.7794)


In [12]:
#q10
print(torch.argmin(prod))
print(torch.argmax(prod))


tensor(1)
tensor(6)


In [13]:
#q11
torch.seed = 7
ten = torch.randn(1,1,1,10)
print(ten)
print(ten.squeeze())

tensor([[[[ 0.8018, -0.2344, -0.7473, -0.5955, -0.5413, -1.2182, -0.5333,
           -0.3847, -0.0714, -0.3385]]]])
tensor([ 0.8018, -0.2344, -0.7473, -0.5955, -0.5413, -1.2182, -0.5333, -0.3847,
        -0.0714, -0.3385])
